# Generated by Django 2.2.3 on 2019-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qauzeemyusuff2scrumy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
